src/venue_django/urls.py
# https://docs.djangoproject.com/en/5.0/topics/http/urls/

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls
from . import settings

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("venue_django_app.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + debug_toolbar_urls()
)

src/venue_django_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("", views.index, name="index"),
    path("talk/<str:slug>", views.talk, name="talk"),
    path("talk/<str:slug>/question", views.talk_question, name="talk_question"),
    path("talk/<str:slug>/questions", views.talk_questions, name="talk_questions"),
    path("talk/<str:slug>/rating", views.talk_rating, name="talk_rating"),
    path("talk/<str:slug>/ratings", views.talk_ratings, name="talk_ratings"),
]

src/venue_django_app/models.py
from django.db import models
from django_prose_editor.fields import ProseEditorField


class Track(models.Model):
    name = models.CharField(max_length=100)
    order = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.name


class Speaker(models.Model):
    name = models.CharField(max_length=200)
    title = models.TextField()
    biography = ProseEditorField(blank=True)
    image = models.ImageField(upload_to="speakers")

    def __str__(self) -> str:
        return self.name


class Talk(models.Model):
    track = models.ForeignKey(Track, on_delete=models.RESTRICT, blank=True, null=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = ProseEditorField(blank=True)
    date = models.DateTimeField()
    display_date = models.BooleanField(default=True)
    speakers = models.ManyToManyField(Speaker)
    enable_questions = models.BooleanField(default=True)
    enable_ratings = models.BooleanField(default=True)

    class Meta:
        ordering = ["date"]

    def __str__(self) -> str:
        return self.name


class Visitor(models.Model):
    id = models.UUIDField(primary_key=True)

    def __str__(self) -> str:
        return self.id.hex


class Question(models.Model):
    talk = models.ForeignKey(Talk, on_delete=models.CASCADE)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE)
    question = models.TextField()

    def __str__(self) -> str:
        return f'"{self.question}"'


class Rating(models.Model):
    talk = models.ForeignKey(Talk, on_delete=models.CASCADE)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField()
    comment = models.TextField()

    class Meta:
        unique_together = ("talk", "visitor")

    def __str__(self) -> str:
        return f'{self.rating}/5: "{self.comment}"'

src/venue/views.py
import constance.settings
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.aggregates import ArrayAgg
from django.http.request import split_domain_port
from django.core.exceptions import BadRequest

from venue.models import Question, Rating, Speaker, Talk, Visitor


def get_domain(request):
    domain, _ = split_domain_port(request.get_host())
    return domain


def get_talk_query(slug):
    return Talk.objects.filter(slug=slug)


@login_required
def login(_: HttpRequest):
    return redirect("index", permanent=False)


def logout(request: HttpRequest):
    session_data_to_keep = [
        (k, request.session.get(k))
        for k in request.session.keys()
        if k == "visitor_id" or k.startswith("talk_rated_")
    ]
    auth_logout(request)
    for key, value in session_data_to_keep:
        request.session[key] = value
    return redirect("index", permanent=False)


def index(request: HttpRequest):
    talks = (
        Talk.objects.order_by("date", "track__order", "track__name")
        .annotate(
            speakers_names=ArrayAgg("speakers__name", ordering=("speakers__name"))
        )
        .values(
            "pk",
            "name",
            "slug",
            "date",
            "display_date",
            "track__name",
            "speakers_names",
        )
    )
    talks = [
        {**talk, "rated": request.session.get("talk_rated_" + str(talk["pk"]), False)}
        for talk in talks
    ]
    return render(request, "venue/index.html", {"talks": talks})


def talk(request: HttpRequest, slug):
    talk = (
        get_talk_query(slug)
        .annotate(
            speakers_ids=ArrayAgg("speakers"),
        )
        .values(
            "pk",
            "name",
            "slug",
            "date",
            "display_date",
            "track__name",
            "description",
            "speakers_ids",
            "enable_questions",
            "enable_ratings",
        )
        .first()
    )
    talk["speakers"] = (
        Speaker.objects.filter(pk__in=talk["speakers_ids"])
        .order_by("name", "title")
        .values("name", "title", "biography", "image")
    )
    return render(
        request,
        "venue/talk.html",
        {
            "talk": talk,
            "talk_rated": request.session.get("talk_rated_" + str(talk["pk"]), False),
        },
    )


def talk_question(request, slug):
    if request.method == "POST":
        question = request.POST.get("question")
        if question is None:
            raise BadRequest()
        if question.strip() == "":
            return redirect("talk", slug, permanent=False)

        visitor, _ = Visitor.objects.get_or_create(id=request.session["visitor_id"])
        talk = get_talk_query(slug).first()
        Question.objects.create(talk=talk, question=question, visitor=visitor).save()
        messages.add_message(request, messages.SUCCESS, "¡Gracias por su pregunta!")
        return redirect("talk", slug, permanent=False)


@login_required
def talk_questions(request: HttpRequest, slug: str):
    if request.method == "GET":
        talk = (
            get_talk_query(slug)
            .annotate(
                speakers_ids=ArrayAgg("speakers"),
            )
            .values(
                "pk",
                "name",
                "slug",
                "date",
                "display_date",
                "track__name",
                "enable_questions",
            )
            .first()
        )
        questions = Question.objects.filter(talk__pk=talk["pk"]).values(
            "pk",
            "question",
        )
        return render(
            request,
            "venue/talk_questions.html",
            {"talk": talk, "questions": questions},
        )


def talk_rating(request, slug):
    if request.method == "POST":
        rating = int(request.POST.get("rating"))
        comment = request.POST.get("comment")
        if rating is None or comment is None:
            raise BadRequest()
        if rating < 1 or rating > 5:
            raise BadRequest()
        if len(comment) > 600:
            raise BadRequest()

        visitor, _ = Visitor.objects.get_or_create(id=request.session["visitor_id"])
        talk = get_talk_query(slug).first()
        Rating.objects.create(
            talk=talk, rating=rating, comment=comment, visitor=visitor
        ).save()
        request.session["talk_rated_" + str(talk.pk)] = True
        return redirect("talk", slug, permanent=False)


@login_required
def talk_ratings(request: HttpRequest, slug: str):
    if request.method == "GET":
        talk = (
            get_talk_query(slug)
            .annotate(
                speakers_ids=ArrayAgg("speakers"),
            )
            .values(
                "pk",
                "name",
                "slug",
                "date",
                "display_date",
                "track__name",
                "enable_ratings",
            )
            .first()
        )
        ratings = Rating.objects.filter(talk__pk=talk["pk"]).values(
            "comment",
            "rating",
        )

        summary = {
            "max": 5,
            "average": 0,
            "stars_per_rating": [
                [True],
                [True, True],
                [True, True, True],
                [
                    True,
                    True,
                    True,
                    True,
                ],
                [
                    True,
                    True,
                    True,
                    True,
                    True,
                ],
            ],
            "count_per_rating": [0, 0, 0, 0, 0],
        }

        if len(ratings) > 0:
            total = 0
            for rating in ratings:
                total += rating["rating"]
                summary["count_per_rating"][rating["rating"] - 1] += 1
            summary["average"] = total / len(ratings)

        return render(
            request,
            "venue/talk_ratings.html",
            {
                "talk": talk,
                "ratings": [r for r in ratings if r["comment"] != ""],
                "summary": summary,
            },
        )

src/venue_django_app/views.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.aggregates import ArrayAgg
from django.http.request import split_domain_port
from django.core.exceptions import BadRequest

from venue_django_app.models import Question, Rating, Speaker, Talk

from venue import ioc


def get_domain(request):
    domain, _ = split_domain_port(request.get_host())
    return domain


def get_talk_query(slug):
    return Talk.objects.filter(slug=slug)


@login_required
def login(_: HttpRequest):
    return redirect("index", permanent=False)


def logout(request: HttpRequest):
    session_data_to_keep = [
        (k, request.session.get(k))
        for k in request.session.keys()
        if k == "visitor_id" or k.startswith("talk_rated_")
    ]
    auth_logout(request)
    for key, value in session_data_to_keep:
        request.session[key] = value
    return redirect("index", permanent=False)


def index(request: HttpRequest):
    talks = (
        Talk.objects.order_by("date", "track__order", "track__name")
        .annotate(
            speakers_names=ArrayAgg("speakers__name", ordering=("speakers__name"))
        )
        .values(
            "pk",
            "name",
            "slug",
            "date",
            "display_date",
            "track__name",
            "speakers_names",
        )
    )
    talks = [
        {**talk, "rated": ioc.visitor_talk_rating_service.has_rated(talk["pk"])}
        for talk in talks
    ]
    return render(request, "venue/index.html", {"talks": talks})


def talk(request: HttpRequest, slug):
    talk = (
        get_talk_query(slug)
        .annotate(
            speakers_ids=ArrayAgg("speakers"),
        )
        .values(
            "pk",
            "name",
            "slug",
            "date",
            "display_date",
            "track__name",
            "description",
            "speakers_ids",
            "enable_questions",
            "enable_ratings",
        )
        .first()
    )
    talk["speakers"] = (
        Speaker.objects.filter(pk__in=talk["speakers_ids"])
        .order_by("name", "title")
        .values("name", "title", "biography", "image")
    )
    return render(
        request,
        "venue/talk.html",
        {
            "talk": talk,
            "talk_rated": ioc.visitor_talk_rating_service.has_rated(talk["pk"]),
        },
    )


def talk_question(request, slug):
    if request.method == "POST":
        question = request.POST.get("question")
        if question is None:
            raise BadRequest()
        if question.strip() == "":
            return redirect("talk", slug, permanent=False)

        ioc.talk_question_creation_command.handle(talk_slug=slug, question=question)

        messages.add_message(request, messages.SUCCESS, "¡Gracias por su pregunta!")
        return redirect("talk", slug, permanent=False)


@login_required
def talk_questions(request: HttpRequest, slug: str):
    if request.method == "GET":
        talk = (
            get_talk_query(slug)
            .annotate(
                speakers_ids=ArrayAgg("speakers"),
            )
            .values(
                "pk",
                "name",
                "slug",
                "date",
                "display_date",
                "track__name",
                "enable_questions",
            )
            .first()
        )
        questions = Question.objects.filter(talk__pk=talk["pk"]).values(
            "pk",
            "question",
        )
        return render(
            request,
            "venue/talk_questions.html",
            {"talk": talk, "questions": questions},
        )


def talk_rating(request, slug):
    if request.method == "POST":
        rating = int(request.POST.get("rating"))
        comment = request.POST.get("comment")
        if rating is None or comment is None:
            raise BadRequest()
        if rating < 1 or rating > 5:
            raise BadRequest()
        if len(comment) > 600:
            raise BadRequest()

        ioc.talk_rating_creation_command.handle(
            talk_slug=slug, rating=rating, comment=comment
        )

        return redirect("talk", slug, permanent=False)


@login_required
def talk_ratings(request: HttpRequest, slug: str):
    if request.method == "GET":
        talk = (
            get_talk_query(slug)
            .annotate(
                speakers_ids=ArrayAgg("speakers"),
            )
            .values(
                "pk",
                "name",
                "slug",
                "date",
                "display_date",
                "track__name",
                "enable_ratings",
            )
            .first()
        )
        ratings = Rating.objects.filter(talk__pk=talk["pk"]).values(
            "comment",
            "rating",
        )

        summary = {
            "max": 5,
            "average": 0,
            "stars_per_rating": [
                [True],
                [True, True],
                [True, True, True],
                [
                    True,
                    True,
                    True,
                    True,
                ],
                [
                    True,
                    True,
                    True,
                    True,
                    True,
                ],
            ],
            "count_per_rating": [0, 0, 0, 0, 0],
        }

        if len(ratings) > 0:
            total = 0
            for rating in ratings:
                total += rating["rating"]
                summary["count_per_rating"][rating["rating"] - 1] += 1
            summary["average"] = total / len(ratings)

        return render(
            request,
            "venue/talk_ratings.html",
            {
                "talk": talk,
                "ratings": [r for r in ratings if r["comment"] != ""],
                "summary": summary,
            },
        )

src/venue_django_app/templates/venue/_talk_admin_menu.html
<a class="x-admin-menu-link {% if request.resolver_match.url_name == 'talk' %}is-active{% endif %}"
    href="{% url 'talk' talk.slug %}">Talk</a>
<a class="x-admin-menu-link {% if request.resolver_match.url_name == 'talk_questions' %}is-active{% endif %}"
    href="{% url 'talk_questions' talk.slug %}">Questions</a>
<a class="x-admin-menu-link {% if request.resolver_match.url_name == 'talk_ratings' %}is-active{% endif %}"
    href="{% url 'talk_ratings' talk.slug %}">Ratings</a>

src/venue_django_app/templates/venue/_talk_information.html
<section class="x-talk-section is-boxed">
    <h1 class="x-talk-title">
        {{ talk.name }}
    </h1>
    {% if talk.track__name or talk.display_date %}
    <div class="x-talk-info">
        {% if talk.track__name %}
        <span class="x-talk-info-track">
            {{ talk.track__name }}
        </span>
        {% endif %}
        {% if talk.display_date %}
        <span class="x-talk-info-when">
            {{ talk.date|date:'H:i' }}
        </span>
        {% endif %}
    </div>
    {% endif %}
    {% if talk.description %}
    <div class="x-talk-description">
        {{ talk.description|safe }}
    </div>
    {% endif %}
</section>

src/venue_django_app/templates/venue/base.html
{% load static %}
{% load venue %}

<!DOCTYPE html>
<html lang="{{config.LANG}}">

<head>
    <meta charset="utf8">
    <meta name="description" content="{{config.EVENT_DESCRIPTION}}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'venue/style.css' %}?v={{VERSION}}">
    <link rel="icon" href="data:image/png;base64,iVBORw0KGgo=">
    {% block meta %}{% endblock %}
    {% if config.EXTRA_CSS %}
    <style>{{ config.EXTRA_CSS|safe }}</style>
    {% endif %}
    {% if config.EXTRA_JS %}
    <script type="text/javascript">{{ config.EXTRA_JS|safe }}</script>
    {% endif %}
</head>

<body>

    <header class="x-header">
        <div class="x-container x-body">
            {% if config.HEADER_IMAGE %}
            <a class="x-header-image" href="/">
                <img src="{% media_url config.HEADER_IMAGE %}" alt="{{ config.EVENT_NAME }}">
            </a>
            {% else %}
            <a class="x-header-title" href="/">
                <h1>{{ config.EVENT_NAME }}</h1>
            </a>
            {% endif %}
        </div>
    </header>

    <div class="x-container x-body">
        {% if user.is_authenticated %}
        <div class="x-admin-menu">
            <div class="x-admin-menu-left">
                {% block admin_menu %}{% endblock %}
            </div>
            <div class="x-admin-menu-right">
                <span class="x-admin-menu-item">Hello {{ user.username }}!</span>
                <a class="x-admin-menu-link" href="{% url 'logout' %}">Log out</a>
            </div>
        </div>
        {% endif %}
        {% for message in messages %}
        <div class="x-talk-notification {{ message.tags }}">
            <span class="icon success">{% include "venue/icons/check.svg" %}</span>
            <span>{{ message }}</span>
        </div>
        {% endfor %}
        {% block body %}{% endblock %}
    </div>

    <footer class="x-footer">
        <div class="x-container x-body">
            <div class="x-footer-left">
                <span>{{ config.EVENT_NAME }}</span>
                {% if config.EVENT_YEAR %}<span>{{ config.EVENT_YEAR }}</span>{% endif %}
            </div>
            <div class="x-footer-right">
                <a href="https://github.com/sirikon/venue" target="_blank"><span class="icon">{% include "venue/icons/git.svg" %}</span> Source Code</a>
            </div>
        </div>
    </footer>

</body>

</html>

src/venue_django_app/templates/venue/index.html
{% extends "venue/base.html" %}

{% block title %}{{ config.EVENT_NAME }}{% endblock %}

{% block body %}
{% if config.BEFORE_TALK_LIST != "<p></p>" %}
<div class="x-before-talk-list">
    {{ config.BEFORE_TALK_LIST|safe }}
</div>
{% endif %}

<div class="x-talk-list">

    {% for talk in talks %}
    <a class="x-talk-list-item {% if talk.rated %}is-rated{% endif %}" href="{% url 'talk' talk.slug %}"
        data-talk-slug="{{ talk.slug }}">
        <div class="x-talk-list-item-arrow">
            {% include "venue/icons/chevron-right.svg" %}
        </div>
        <h3 class="x-talk-list-item-title">
            {% include "venue/icons/check.svg" %}
            <span>{{ talk.name }}</span>
        </h3>
        <div class="x-talk-list-item-info">
            <span class="x-talk-list-item-info-speaker">
                {{ talk.speakers_names|join:', ' }}
            </span>
            {% if talk.track__name %}
            <span class="x-talk-list-item-info-track">
                {{ talk.track__name }}
            </span>
            {% endif %}
            {% if talk.display_date %}
            <span class="x-talk-list-item-info-when">
                {{ talk.date|date:'H:i' }}
            </span>
            {% endif %}
        </div>
    </a>
    {% endfor %}

</div>

{% if config.AFTER_TALK_LIST != "<p></p>" %}
<div class="x-after-talk-list">
    {{ config.AFTER_TALK_LIST|safe }}
</div>
{% endif %}
{% endblock %}

src/venue_django_app/templates/venue/talk.html
{% extends "venue/base.html" %}
{% load static %}
{% load venue %}

{% block title %}{{ talk.name }} | {{ config.EVENT_NAME }}{% endblock %}

{% block admin_menu %}
{% include "venue/_talk_admin_menu.html" %}
{% endblock %}

{% block meta %}
<meta name="twitter:card" content="summary" />
<meta property="og:title" content="{{ talk.name }}. ¡Dame feedback!" />
<meta property="og:type" content="website" />
{% if talk.speakers %}
<meta property="og:image" content="{% media_url talk.speakers.0.image %}">
{% endif %}
<meta property="og:description" content="Por {{ talk.speakers.0.name }} en {{ config.EVENT_NAME }}" />
{% endblock %}

{% block body %}

{% if talk_rated %}
<div class="x-talk-notification success">
    <span class="icon success">{% include "venue/icons/check.svg" %}</span>
    <span>¡Gracias por su valoración!</span>
</div>
{% endif %}

<div class="x-talk" data-talk-slug="{{ talk.slug }}">
    {% include "venue/_talk_information.html" %}

    {% for speaker in talk.speakers %}
    <section class="x-talk-section x-talk-speaker">
        <div class="x-talk-speaker-image" style="background-image:url({% get_media_prefix %}{{ speaker.image }});;">
        </div>
        <div class="x-talk-speaker-info">
            <h2 class="x-talk-speaker-info-name">
                {{ speaker.name }}
            </h2>
            <span class="x-talk-speaker-info-title">
                {{ speaker.title }}
            </span>
            {{ speaker.biography|safe }}
        </div>
    </section>
    {% endfor %}

    {% if talk.enable_questions %}
    <section class="x-talk-section is-boxed" data-section="question">
        <h2 class="x-talk-section-title">Haz una pregunta</h2>
        <form action="{% url 'talk_question' talk.slug %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <textarea class="x-talk-textarea" name="question" maxlength="600" required
                placeholder="¿Qué quieres preguntar?"></textarea>
            <input class="x-talk-button" type="submit" value="Enviar">
        </form>
    </section>
    {% endif %}

    {% if not talk_rated and talk.enable_ratings %}
    <section class="x-talk-section is-boxed" data-section="rating">
        <h2 class="x-talk-section-title">Valora la charla</h2>
        <form action="{% url 'talk_rating' talk.slug %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="x-stars">
                <label for="star-1">
                    {% include "venue/icons/star.svg" %}
                </label>
                <input id="star-1" type="radio" name="rating" value="1" checked="checked">
                <label for="star-2">
                    {% include "venue/icons/star.svg" %}
                </label>
                <input id="star-2" type="radio" name="rating" value="2" checked="checked">
                <label for="star-3">
                    {% include "venue/icons/star.svg" %}
                </label>
                <input id="star-3" type="radio" name="rating" value="3" checked="checked">
                <label for="star-4">
                    {% include "venue/icons/star.svg" %}
                </label>
                <input id="star-4" type="radio" name="rating" value="4">
                <label for="star-5">
                    {% include "venue/icons/star.svg" %}
                </label>
                <input id="star-5" type="radio" name="rating" value="5">
            </div>
            <textarea class="x-talk-textarea" name="comment" maxlength="600"
                placeholder="Deja un comentario... si lo ves oportuno :)"></textarea>
            <input class="x-talk-button" type="submit" value="Enviar">
        </form>
    </section>
    {% endif %}

</div>
{% endblock %}

src/venue_django_app/templates/venue/talk_questions.html
{% extends "venue/base.html" %}
{% load static %}

{% block title %}Questions | {{ talk.name }} | {{ config.EVENT_NAME }}{% endblock %}

{% block admin_menu %}
{% include "venue/_talk_admin_menu.html" %}
{% endblock %}

{% block body %}
{% if not talk.enable_questions %}
<div class="x-talk-notification warning">
    <span class="icon success">{% include "venue/icons/check.svg" %}</span>
    <span>⚠️ Questions are <b>disabled</b> in this talk. <a
            href="/admin/venue/talk/{{ talk.pk }}/change/#id_enable_questions">Edit the talk in the admin panel</a> to
        enable it.</span>
</div>
{% endif %}

<div class="x-talk" data-talk-slug="{{ talk.slug }}">
    {% include "venue/_talk_information.html" %}

    <section class="x-talk-section is-boxed">
        <h2 class="x-talk-section-title">
            Preguntas recibidas
        </h2>

        <form class="x-talk-question-filter">
            <label for="see_fav_only">Mostrar solo favoritos</label>
            <input type="checkbox" id="see_fav_only" onchange="checkboxChangeHandler()">
        </form>

        <div class="x-talk-question-list">
            {% for question in questions %}
            <div class="x-talk-question-list-item" data-question-id="{{ question.pk }}">
                <p>
                    {{ question.question }}
                </p>
                <div class="x-talk-question-list-item-actions">
                    <button class="x-talk-question-list-item-actions-fav" type="button"
                        data-question-id="{{ question.pk }}" onclick="setFav(this, true)">
                        {% include "venue/icons/star.svg" %}
                    </button>
                    <button class="x-talk-question-list-item-actions-unfav" type="button"
                        data-question-id="{{ question.pk }}" onclick="setFav(this, false)">
                        {% include "venue/icons/star.svg" %}
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>

    </section>
</div>

<script type="text/javascript">

    const seeFavOnlyCheckbox = document.getElementById("see_fav_only");
    const questionListDiv = document.querySelector(".x-talk-question-list");

    const storedState = localStorage.getItem("fav_state");
    const state = storedState ? JSON.parse(storedState) : {
        seeFavOnly: false,
        favs: []
    }

    function render() {
        seeFavOnlyCheckbox.checked = state.seeFavOnly;

        questionListDiv.classList.toggle("is-fav-only", state.seeFavOnly);
        document.querySelectorAll(".x-talk-question-list-item").forEach((el) => {
            const questionId = parseInt(el.getAttribute("data-question-id"));
            el.classList.toggle("is-fav", state.favs.indexOf(questionId) >= 0);
        });
    }

    function saveState() {
        localStorage.setItem("fav_state", JSON.stringify(state));
    }

    function checkboxChangeHandler() {
        state.seeFavOnly = seeFavOnlyCheckbox.checked;

        saveState();
        render();
    }

    function setFav(el, value) {
        const questionId = parseInt(el.getAttribute("data-question-id"));

        const favIndex = state.favs.indexOf(questionId);
        if (favIndex >= 0 && !value) {
            state.favs.splice(favIndex, 1);
        }

        if (favIndex === -1 && value) {
            state.favs.push(questionId);
        }

        saveState();
        render();
    }

    render();

</script>

{% endblock %}

src/venue_django_app/templates/venue/talk_ratings.html
{% extends "venue/base.html" %}
{% load static %}

{% block title %}Questions | {{ talk.name }} | {{ config.EVENT_NAME }}{% endblock %}

{% block admin_menu %}
{% include "venue/_talk_admin_menu.html" %}
{% endblock %}

{% block body %}
{% if not talk.enable_ratings %}
<div class="x-talk-notification warning">
    <span class="icon success">{% include "venue/icons/check.svg" %}</span>
    <span>⚠️ Ratings are <b>disabled</b> in this talk. <a
            href="/admin/venue/talk/{{ talk.pk }}/change/#id_enable_ratings">Edit the talk in the admin panel</a> to
        enable it.</span>
</div>
{% endif %}

<div class="x-talk" data-talk-slug="{{ talk.slug }}">
    {% include "venue/_talk_information.html" %}

    <section class="x-talk-section">
        <div class="x-talk-rating">

            <div class="x-talk-rating-stars">
                <div class="x-talk-rating-stars-numbers">
                    {% for i in summary.count_per_rating %}
                    <span>{{ i }}</span>
                    {% endfor %}
                </div>
                <div class="x-talk-rating-stars-bars">
                    {% for i in summary.stars_per_rating %}
                    <div>
                        {% for _ in i %}
                        {% include "venue/icons/star.svg" %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="x-talk-rating-average">
                <span class="x-talk-rating-average-value">
                    {%if summary.average != 0%}{{summary.average|floatformat:"-2" }}{%else%}--{%endif%}</span><span
                    class="x-talk-rating-average-max">/{{ summary.max }}</span>
            </div>

        </div>
    </section>

    <section class="x-talk-section is-boxed">
        <h2 class="x-talk-section-title">
            Comentarios
        </h2>

        <p class="x-talk-section-advice">A continuación aparecen todos los comentarios que la gente ha puesto
            acompañando a la nota de la charla. Por desgracia, a veces hay que lidiar con los comentarios de personas
            que no tienen sus capacidades sociales del todo desarrolladas, que son incapaces de valorar el esfuerzo de
            los demás, o que simplemente son tóxicas.</p>
        <p class="x-talk-section-advice">Coge aire, tómatelo con calma, y recuerda que si te hemos llamado para
            participar es por algo. Nos ha encantado tenerte por aquí.</p>

        {% for rating in ratings %}
        <div class="x-talk-comment">
            <p>
                {{ rating.comment }} — <span class="x-talk-comment-stars">
                    {{ rating.rating }}
                    {% include "venue/icons/star.svg" %}
                </span>
            </p>
        </div>
        {% endfor %}
    </section>
</div>
{% endblock %}